// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "callback of authentication by authing",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "authing code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "redirect uri",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.UserDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "duplicate_creating"
                        }
                    }
                }
            }
        },
        "/v1/dataset": {
            "post": {
                "description": "create dataset",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Dataset"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "body of creating dataset",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.datasetCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/app.DatasetDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "duplicate_creating"
                        }
                    }
                }
            }
        },
        "/v1/dataset/{owner}": {
            "get": {
                "description": "list dataset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dataset"
                ],
                "summary": "List",
                "responses": {}
            }
        },
        "/v1/dataset/{owner}/{id}": {
            "put": {
                "description": "update property of dataset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dataset"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of dataset",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of updating dataset",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.datasetUpdateRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/v1/dataset/{owner}/{name}": {
            "get": {
                "description": "get dataset",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Dataset"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of dataset",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of dataset",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.DatasetDTO"
                        }
                    }
                }
            }
        },
        "/v1/model": {
            "post": {
                "description": "create model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Model"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "body of creating model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.modelCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/app.ModelDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "duplicate_creating"
                        }
                    }
                }
            }
        },
        "/v1/model/{owner}": {
            "get": {
                "description": "list model",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Model"
                ],
                "summary": "List",
                "responses": {}
            }
        },
        "/v1/model/{owner}/{id}": {
            "put": {
                "description": "update property of model",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Model"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of updating model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.modelUpdateRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/v1/model/{owner}/{id}/dataset/relation": {
            "put": {
                "description": "add related dataset to model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Model"
                ],
                "summary": "AddRelatedDataset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of model",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of related dataset",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.relatedResourceAddRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/app.ResourceDTO"
                        }
                    }
                }
            },
            "delete": {
                "description": "remove related dataset to model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Model"
                ],
                "summary": "RemoveRelatedDataset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of model",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of related dataset",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.relatedResourceRemoveRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/model/{owner}/{id}/tags": {
            "put": {
                "description": "set tags for model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Model"
                ],
                "summary": "SetTags",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of model",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of model",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of tags",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.resourceTagsUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/model/{owner}/{name}": {
            "get": {
                "description": "get model",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Model"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of model",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of model",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ModelDTO"
                        }
                    }
                }
            }
        },
        "/v1/project": {
            "post": {
                "description": "create project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "body of creating project",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.projectCreateRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/v1/project/{owner}": {
            "get": {
                "description": "list project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of project",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/project/{owner}/{id}": {
            "put": {
                "description": "update project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of project",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of project",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of updating project",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.projectUpdateRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "fork project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Fork",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of forked project",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of forked project",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/project/{owner}/{id}/dataset/relation": {
            "put": {
                "description": "add related dataset to project",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "AddRelatedDataset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of project",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of project",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of related dataset",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.relatedResourceAddRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/app.ResourceDTO"
                        }
                    }
                }
            },
            "delete": {
                "description": "remove related dataset to project",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "RemoveRelatedDataset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of project",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of project",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of related dataset",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.relatedResourceRemoveRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/project/{owner}/{id}/model/relation": {
            "put": {
                "description": "add related model to project",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "AddRelatedModel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of project",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of project",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of related model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.relatedResourceAddRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/app.ResourceDTO"
                        }
                    }
                }
            },
            "delete": {
                "description": "remove related model to project",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "RemoveRelatedModel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of project",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of project",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of related model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.relatedResourceRemoveRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/project/{owner}/{id}/tags": {
            "put": {
                "description": "set tags for project",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "SetTags",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of project",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of project",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body of updating project",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.resourceTagsUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/project/{owner}/{name}": {
            "get": {
                "description": "get project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner of project",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of project",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/v1/tags/{type}": {
            "get": {
                "description": "list tags",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.DomainTagsDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "get": {
                "description": "get user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account",
                        "name": "account",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.userDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "resource_not_exists"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            },
            "put": {
                "description": "update user basic info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update",
                "responses": {}
            },
            "post": {
                "description": "create user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "body of creating user",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.userCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/app.UserDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "duplicate_creating"
                        }
                    }
                }
            }
        },
        "/v1/user/activity": {
            "get": {
                "description": "list activitys",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.ActivityDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            }
        },
        "/v1/user/follower/{account}": {
            "get": {
                "description": "list followers",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Follower"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.FollowDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            }
        },
        "/v1/user/following": {
            "post": {
                "description": "add a following",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Following"
                ],
                "parameters": [
                    {
                        "description": "body of creating following",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.followingCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "402": {
                        "description": "Payment Required",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "resource_not_exists"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "duplicate_creating"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            }
        },
        "/v1/user/following/{account}": {
            "get": {
                "description": "list followings",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Following"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.FollowDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            },
            "delete": {
                "description": "remove a following",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Following"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "the account of following",
                        "name": "account",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            }
        },
        "/v1/user/like": {
            "get": {
                "description": "list likes",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.LikeDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            },
            "post": {
                "description": "create a like",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "parameters": [
                    {
                        "description": "body of creating like",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.likeCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "402": {
                        "description": "Payment Required",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "resource_not_exists"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "duplicate_creating"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete a like",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "parameters": [
                    {
                        "description": "body of deleting like",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.likeDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "402": {
                        "description": "Payment Required",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "resource_not_exists"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            }
        },
        "/{account}": {
            "get": {
                "description": "get info of login",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.LoginDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "system_error"
                        }
                    }
                }
            }
        },
        "/{account}/gitlab": {
            "get": {
                "description": "get code platform info of user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.platformInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "bad_request_param"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "not_allowed"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.ActivityDTO": {
            "type": "object",
            "properties": {
                "resource": {
                    "$ref": "#/definitions/app.ResourceDTO"
                },
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "app.DatasetDTO": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "repo_id": {
                    "type": "string"
                },
                "repo_type": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "app.DomainTagsDTO": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Tags"
                    }
                }
            }
        },
        "app.FollowDTO": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "avatar_id": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                }
            }
        },
        "app.LikeDTO": {
            "type": "object",
            "properties": {
                "resource": {
                    "$ref": "#/definitions/app.ResourceDTO"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "app.LoginDTO": {
            "type": "object",
            "properties": {
                "info": {
                    "type": "string"
                }
            }
        },
        "app.ModelDTO": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "repo_id": {
                    "type": "string"
                },
                "repo_type": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "app.ResourceDTO": {
            "type": "object",
            "properties": {
                "cover_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "fork_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "like_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "object",
                    "properties": {
                        "avatar_id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "type": {
                    "type": "string"
                },
                "update_at": {
                    "type": "string"
                }
            }
        },
        "app.UserDTO": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "avatar_id": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "follower_count": {
                    "type": "integer"
                },
                "following_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "controller.datasetCreateRequest": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "repo_type": {
                    "type": "string"
                }
            }
        },
        "controller.datasetUpdateRequest": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "controller.followingCreateRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                }
            }
        },
        "controller.likeCreateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "controller.likeDeleteRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "controller.modelCreateRequest": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "repo_type": {
                    "type": "string"
                }
            }
        },
        "controller.modelUpdateRequest": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "controller.platformInfo": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "controller.projectCreateRequest": {
            "type": "object",
            "properties": {
                "cover_id": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "repo_type": {
                    "type": "string"
                },
                "training": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "controller.projectUpdateRequest": {
            "type": "object",
            "properties": {
                "cover_id": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "controller.relatedResourceAddRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "controller.relatedResourceRemoveRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "controller.resourceTagsUpdateRequest": {
            "type": "object",
            "properties": {
                "add": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "remove": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controller.userCreateRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controller.userDetail": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "avatar_id": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "follower_count": {
                    "type": "integer"
                },
                "following_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_follower": {
                    "type": "boolean"
                }
            }
        },
        "domain.Tags": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "kind": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
